import { Tags } from "lucide-react";

import { ProjectCategoryDialog, DeleteProjectCategoryDialog } from "@/modules/project-categories/components/category-dialog";
import { ProjectCategoryIcon } from "@/modules/project-categories/icons";
import { getProjectCategoryList } from "@/modules/project-categories/queries";
import { ServiceRouteToast } from "@/modules/services/components/service-route-toast";

type PageProps = { searchParams: Promise<{ success?: string; error?: string }> };

export default async function ProjectCategoriesPage({ searchParams }: PageProps) {
  const [categories, messages] = await Promise.all([getProjectCategoryList(), searchParams]);
  return <div className="mx-auto w-full max-w-[1280px] space-y-5">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-[1.75rem] font-bold leading-10">تصنيفات المشاريع</h1><p className="mt-1 text-sm leading-6 text-text-secondary">إدارة التصنيفات والأيقونات المستخدمة لتعريف المشاريع بصرياً.</p></div><ProjectCategoryDialog /></header>
    <ServiceRouteToast cleanHref="/dashboard/project-categories" error={messages.error} success={messages.success} />
    <section aria-label="تصنيفات المشاريع" className="overflow-hidden rounded-xl border border-border bg-card shadow-[var(--shadow-rest)]">
      {categories.length ? <><div className="hidden md:block"><table className="w-full table-fixed text-start text-sm"><thead className="bg-dashboard-canvas/65 text-xs font-medium text-muted-foreground"><tr className="h-11"><th className="w-auto px-4 text-start font-medium">التصنيف</th><th className="w-36 px-4 text-start font-medium">المشاريع</th><th className="w-32 px-4 text-start font-medium">الحالة</th><th className="w-24 px-4 text-start font-medium">الترتيب</th><th className="w-24 px-3"><span className="sr-only">الإجراءات</span></th></tr></thead><tbody>{categories.map((category) => <tr className="h-16 border-t border-border/80 hover:bg-dashboard-hover/55" key={category.id}><td className="px-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-md bg-primary-soft text-primary"><ProjectCategoryIcon iconKey={category.iconKey} /></span><div className="min-w-0"><span className="block truncate font-semibold">{category.name}</span>{category.description ? <span className="mt-0.5 block truncate text-xs text-muted-foreground">{category.description}</span> : null}</div></div></td><td className="px-4 tabular-nums text-text-secondary">{category.projectCount}</td><td className="px-4"><CategoryStatus active={category.isActive} /></td><td className="px-4 tabular-nums text-text-secondary">{category.sortOrder}</td><td className="px-3"><div className="flex justify-end gap-1"><ProjectCategoryDialog category={category} /><DeleteProjectCategoryDialog category={category} /></div></td></tr>)}</tbody></table></div><div className="divide-y divide-border md:hidden">{categories.map((category) => <article className="grid grid-cols-[minmax(0,1fr)_auto] gap-3 p-4" key={category.id}><div className="flex min-w-0 gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-primary-soft text-primary"><ProjectCategoryIcon iconKey={category.iconKey} /></span><div className="min-w-0"><h2 className="truncate font-semibold">{category.name}</h2><p className="mt-1 text-xs text-muted-foreground">{category.projectCount} مشروع · الترتيب {category.sortOrder}</p><div className="mt-2"><CategoryStatus active={category.isActive} /></div></div></div><div className="flex"><ProjectCategoryDialog category={category} /><DeleteProjectCategoryDialog category={category} /></div></article>)}</div></> : <div className="grid min-h-72 place-items-center px-6 py-12 text-center"><div><span className="mx-auto grid size-10 place-items-center rounded-md bg-secondary text-muted-foreground"><Tags className="size-5" /></span><h2 className="mt-4 text-lg font-semibold">لا توجد تصنيفات بعد</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-text-secondary">أنشئ تصنيفاً لاستخدامه اختيارياً في بطاقات ومعلومات المشاريع.</p><div className="mt-5"><ProjectCategoryDialog compact /></div></div></div>}
    </section>
  </div>;
}

function CategoryStatus({ active }: { active: boolean }) { return <span className={`inline-flex min-h-6 w-fit items-center gap-1.5 rounded-full px-2.5 text-xs font-medium ${active ? "bg-success-soft text-success" : "bg-secondary text-text-secondary"}`}><span className="size-1.5 rounded-full bg-current" />{active ? "نشط" : "غير نشط"}</span>; }
